SCHEDULER_PARAMETERS: "-N 1 -M escori -q compile -t 30"

stages:
  - validate
  - regression

validate_cori_testsuite:
  tags: ["cori"]
  stage: validate
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"'
      when: manual
  script:
    - module load python
    - conda create -n buildtest python=3.8
    - source activate buildtest
    - source setup.sh    
    - git clone https://github.com/buildtesters/buildtest-cori/
    - cd buildtest-cori
    - mkdir -p $HOME/.buildtest
    - cp .buildtest/config.yml $HOME/.buildtest/config.yml
    - buildtest config validate
    - buildtest buildspec find --root $PWD
    - source deactivate 
    - conda env remove -n buildtest -y
    
cori_pr_regression_test:
  tags: ["cori"]
  stage: regression
  rules:
    - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event" || $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"'
      when: manual
    
  script: 
    - env | grep CI_
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME
    - module load python
    - echo "$CI_PIPELINE_SOURCE"
    - whoami
    - git branch
    - conda create -n buildtest python=3.8
    - source activate buildtest
    - source setup.sh    
    - pip install -r docs/requirements.txt
    - rm -rf ~/.buildtest/
    - coverage run -m pytest -vra tests
    - coverage report -m
    # CODECOV_TOKEN environment must be set, this value is stored in CI/CD variable SECRET_CODECOV_TOKEN at https://gitlab.nersc.gov/nersc/consulting/buildtest/-/settings/ci_cd
    - export CODECOV_TOKEN=$SECRET_CODECOV_TOKEN
    - bash <(curl -s https://codecov.io/bash)
    - source deactivate
    - conda env remove -n buildtest -y
