name: Black Formatter

on:
  push:
    branches:
      - master
      - devel
  pull_request:
      branches:
        - master
        - devel

jobs:
  blackformat:
    runs-on: ubuntu-latest
    steps:

      # use isort github action see https://pycqa.github.io/isort/docs/configuration/github_action.html
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: jamescurtin/isort-action@master
        with:
          #requirementsFiles: "requirements.txt docs/requirements.txt"
          sortPaths: "buildtest tests docs"
      # use black github action see https://black.readthedocs.io/en/stable/integrations/github_actions.html
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "buildtest tests scripts"

      - name: Check imports with pyflakes
        run: |
          pip install pyflakes
          pyflakes buildtest tests scripts
