name: Mirror and run GitLab CI

on: [push]

jobs:
  nersc_mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror and trigger CI job at https://software.nersc.gov 
      uses: stenongithub/gitlab-mirror-and-ci-action@0.2.7
      with:
        args: "https://software.nersc.gov/siddiq90/buildtest"
      env:
        GITLAB_HOSTNAME: "software.nersc.gov"
        GITLAB_USERNAME: "siddiq90"
        GITLAB_PASSWORD: ${{ secrets.CORI_GITLAB_PASSWORD }} 
        GITLAB_PROJECT_ID: "176"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        POLL_TIMEOUT: "300" 

  olcf_mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror and trigger CI job at https://code.ornl.gov 
      uses: stenongithub/gitlab-mirror-and-ci-action@0.2.7
      with:
        args: "https://code.ornl.govv/shahzebsiddiqui/buildtest"
      env:
        GITLAB_HOSTNAME: "code.ornl.gov"
        GITLAB_USERNAME: "shahzebsiddiqui"
        GITLAB_PASSWORD: ${{ secrets.OLCF_GITLAB_PASSWORD }} 
        GITLAB_PROJECT_ID: "8241"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        POLL_TIMEOUT: "300" 
